name: perfume
description: Perfume Flutter App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/CormorantGaramond-Light.ttf
          weight: 300
        - asset: assets/fonts/CormorantGaramond-Regular.ttf
          weight: 400
        - asset: assets/fonts/CormorantGaramond-Medium.ttf
          weight: 500

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icon/